# Generated by Django 4.2.16 on 2024-11-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('language', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contestant1_name', models.CharField(max_length=100)),
                ('contestant1_grade', models.DecimalField(decimal_places=0, max_digits=2)),
                ('contestant2_name', models.CharField(max_length=100)),
                ('contestant2_grade', models.DecimalField(decimal_places=0, max_digits=2)),
                ('contestant3_name', models.CharField(max_length=100)),
                ('contestant3_grade', models.DecimalField(decimal_places=0, max_digits=2)),
                ('contestant4_name', models.CharField(max_length=100, null=True)),
                ('contestant4_grade', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('teachers', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.language')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
    ]
