# Generated by Django 4.2.16 on 2024-11-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
