# Generated by Django 4.2.16 on 2024-11-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_approved_team_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='approval_file',
            field=models.FileField(blank=True, null=True, upload_to='approval_files/'),
        ),
    ]
