# Generated by Django 4.2.16 on 2024-11-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_approval_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='missing',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='contestant1_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='team',
            name='contestant2_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='team',
            name='contestant3_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='team',
            name='contestant4_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='teachers',
            field=models.TextField(max_length=128),
        ),
    ]
