# Generated by Django 4.2.16 on 2024-11-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=228, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_email',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=228, unique=True),
        ),
    ]
