# Generated by Django 4.2.6 on 2024-11-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_deadline', models.DateTimeField()),
                ('joining_closed', models.BooleanField(default=False)),
            ],
        ),
    ]
